#pragma once

// Vendored unmodified from TopoVLA @ 0da5050, native_depth_yolo/src/ddgng.hpp.
// TopoVLA is a separate repository; do not edit this file here, re-vendor it
// instead. Pulled in for om6dof_dd_gng's topo_gng_node (M2): pure C++, no
// Windows/GL/YOLO dependencies, and already covered by
// TopoVLA/native_ddgng_yolo/tests/ddgng_invariants.cpp upstream.

#include <algorithm>
#include <cstdint>
#include <limits>
#include <random>
#include <utility>
#include <vector>

struct GngPoint3f {
    float x = 0.0F;
    float y = 0.0F;
    float z = 0.0F;
};

// Dynamic Growing Neural Gas core used by the optional DD-GNG + YOLO mode.
// Node degrees are tracked explicitly so isolated-node removal does not scan
// the complete adjacency matrix for every online update.
class DynamicGrowingNeuralGas {
public:
    explicit DynamicGrowingNeuralGas(int maxNodes)
        : capacity_(maxNodes), nodes_(maxNodes), nodeIds_(maxNodes), errors_(maxNodes),
          utility_(maxNodes), degrees_(maxNodes),
          ages_(static_cast<size_t>(maxNodes) * maxNodes, kNoEdge), rng_(7) {
        neighbors_.reserve(maxNodes);
    }

    void reset() {
        count_ = 0;
        totalUpdates_ = 0;
        nextNodeId_ = 1;
        rng_.seed(7);
        std::fill(nodeIds_.begin(), nodeIds_.end(), 0);
        std::fill(errors_.begin(), errors_.end(), 0.0F);
        std::fill(utility_.begin(), utility_.end(), 0.0F);
        std::fill(degrees_.begin(), degrees_.end(), 0);
        std::fill(ages_.begin(), ages_.end(), kNoEdge);
    }

    void partialFit(const std::vector<GngPoint3f>& points, int updates) {
        if (points.size() < 2 || updates <= 0) return;
        if (count_ < 2) initialize(points);
        if (count_ < 2) return;

        std::uniform_int_distribution<size_t> pick(0, points.size() - 1);
        for (int update = 0; update < updates; ++update) {
            const GngPoint3f point = points[pick(rng_)];
            int winner = -1;
            int second = -1;
            float best = std::numeric_limits<float>::max();
            float next = std::numeric_limits<float>::max();

            for (int i = 0; i < count_; ++i) {
                const float dx = nodes_[i].x - point.x;
                const float dy = nodes_[i].y - point.y;
                const float dz = nodes_[i].z - point.z;
                const float distance = dx * dx + dy * dy + dz * dz;
                if (distance < best) {
                    next = best;
                    second = winner;
                    best = distance;
                    winner = i;
                } else if (distance < next) {
                    next = distance;
                    second = i;
                }
            }
            if (winner < 0 || second < 0) continue;

            neighbors_.clear();
            const size_t row = static_cast<size_t>(winner) * capacity_;
            for (int i = 0; i < count_; ++i) {
                int16_t& age = ages_[row + i];
                if (age >= 0) {
                    neighbors_.push_back(i);
                    ++age;
                    ages_[static_cast<size_t>(i) * capacity_ + winner] = age;
                }
            }

            errors_[winner] += best;
            utility_[winner] += next - best;
            moveToward(nodes_[winner], point, 0.08F);
            for (const int neighbor : neighbors_)
                moveToward(nodes_[neighbor], point, 0.0008F);
            setEdge(winner, second, 0);

            bool removedEdge = false;
            for (int i = 0; i < count_; ++i) {
                if (ages_[row + i] > 50) {
                    setEdge(winner, i, kNoEdge);
                    removedEdge = true;
                }
            }
            if (removedEdge) removeIsolated();

            for (int i = 0; i < count_; ++i) {
                errors_[i] *= 0.9995F;
                utility_[i] *= 0.9995F;
            }
            ++totalUpdates_;
            if (totalUpdates_ % 100 == 0) insertNode();
        }
    }

    void copyGraph(std::vector<GngPoint3f>& nodes,
                   std::vector<uint32_t>& nodeIds,
                   std::vector<std::pair<uint16_t, uint16_t>>& edges) const {
        nodes.assign(nodes_.begin(), nodes_.begin() + count_);
        nodeIds.assign(nodeIds_.begin(), nodeIds_.begin() + count_);
        edges.clear();
        for (int a = 0; a < count_; ++a) {
            for (int b = a + 1; b < count_; ++b) {
                if (edge(a, b) >= 0)
                    edges.emplace_back(static_cast<uint16_t>(a),
                                       static_cast<uint16_t>(b));
            }
        }
    }

private:
    static constexpr int16_t kNoEdge = -1;

    static void moveToward(GngPoint3f& node, const GngPoint3f& point,
                           float rate) {
        node.x += rate * (point.x - node.x);
        node.y += rate * (point.y - node.y);
        node.z += rate * (point.z - node.z);
    }

    int16_t edge(int a, int b) const {
        return ages_[static_cast<size_t>(a) * capacity_ + b];
    }

    void setEdge(int a, int b, int16_t age) {
        if (a < 0 || b < 0 || a >= capacity_ || b >= capacity_) return;
        const bool existed = edge(a, b) >= 0;
        const bool exists = age >= 0;
        ages_[static_cast<size_t>(a) * capacity_ + b] = age;
        ages_[static_cast<size_t>(b) * capacity_ + a] = age;
        if (a != b && existed != exists) {
            const int delta = exists ? 1 : -1;
            degrees_[a] += delta;
            degrees_[b] += delta;
        }
    }

    void initialize(const std::vector<GngPoint3f>& points) {
        std::uniform_int_distribution<size_t> pick(0, points.size() - 1);
        const size_t first = pick(rng_);
        size_t second = pick(rng_);
        while (second == first) second = pick(rng_);
        nodes_[0] = points[first];
        nodes_[1] = points[second];
        nodeIds_[0] = nextNodeId_++;
        nodeIds_[1] = nextNodeId_++;
        count_ = 2;
        degrees_[0] = degrees_[1] = 0;
        setEdge(0, 1, 0);
    }

    void recomputeDegrees() {
        std::fill(degrees_.begin(), degrees_.end(), 0);
        for (int a = 0; a < count_; ++a) {
            for (int b = a + 1; b < count_; ++b) {
                if (edge(a, b) >= 0) {
                    ++degrees_[a];
                    ++degrees_[b];
                }
            }
        }
    }

    void removeNode(int index) {
        if (count_ <= 2 || index < 0 || index >= count_) return;
        const int last = count_ - 1;
        if (index != last) {
            nodes_[index] = nodes_[last];
            nodeIds_[index] = nodeIds_[last];
            errors_[index] = errors_[last];
            utility_[index] = utility_[last];
            for (int k = 0; k < last; ++k) {
                const int16_t moved = edge(last, k);
                setEdge(index, k, moved);
            }
            setEdge(index, index, kNoEdge);
        }
        for (int k = 0; k < count_; ++k) setEdge(last, k, kNoEdge);
        errors_[last] = utility_[last] = 0.0F;
        nodeIds_[last] = 0;
        --count_;
        recomputeDegrees();
    }

    void removeIsolated() {
        while (count_ > 2) {
            const auto isolated = std::find(degrees_.begin(),
                                            degrees_.begin() + count_, 0);
            if (isolated == degrees_.begin() + count_) break;
            removeNode(static_cast<int>(isolated - degrees_.begin()));
        }
    }

    void insertNode() {
        if (count_ < 2) return;
        if (count_ >= capacity_) {
            const int weakest = static_cast<int>(
                std::min_element(utility_.begin(), utility_.begin() + count_) -
                utility_.begin());
            removeNode(weakest);
            removeIsolated();
        }
        if (count_ < 2) return;
        const int q = static_cast<int>(
            std::max_element(errors_.begin(), errors_.begin() + count_) -
            errors_.begin());
        int f = -1;
        for (int i = 0; i < count_; ++i) {
            if (edge(q, i) >= 0 && (f < 0 || errors_[i] > errors_[f])) f = i;
        }
        if (f < 0 || count_ >= capacity_) return;
        const int r = count_++;
        nodes_[r] = {(nodes_[q].x + nodes_[f].x) * 0.5F,
                     (nodes_[q].y + nodes_[f].y) * 0.5F,
                     (nodes_[q].z + nodes_[f].z) * 0.5F};
        nodeIds_[r] = nextNodeId_++;
        errors_[q] *= 0.5F;
        errors_[f] *= 0.5F;
        errors_[r] = errors_[q];
        utility_[r] = (utility_[q] + utility_[f]) * 0.5F;
        degrees_[r] = 0;
        setEdge(q, f, kNoEdge);
        setEdge(q, r, 0);
        setEdge(f, r, 0);
    }

    int capacity_;
    int count_ = 0;
    uint64_t totalUpdates_ = 0;
    uint32_t nextNodeId_ = 1;
    std::vector<GngPoint3f> nodes_;
    std::vector<uint32_t> nodeIds_;
    std::vector<float> errors_;
    std::vector<float> utility_;
    std::vector<int> degrees_;
    std::vector<int16_t> ages_;
    std::vector<int> neighbors_;
    std::mt19937 rng_;
};
